version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=cvworld
      - MYSQL_ROOT_PASSWORD=cvworld
      - MYSQL_DATABASE=cvworld
    networks:
      - mynetwork

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:80
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://cvworld:cvworld@mysql:3306/cvworld
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=user
      - ADMIN_NAME=user
      - JWT_SECRET=secret
    command: sh -c "npx prisma migrate deploy --preview-feature && npm run start"
    networks:
      - mynetwork

  client:
    build:
      context: ./packages/client/flutter_client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    networks:
      - mynetwork
    
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
