version: '3'
services:
  mysql:
    container_name: cvworld-mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./packages/server/.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  server:
    container_name: cvworld-server
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql
    env_file:
      - ./packages/server/.env
    command: sh -c "npx prisma migrate deploy && npm run start"
    volumes:
      - ./public:/app/public
    networks:
      - mynetwork

  client:
    container_name: cvworld-client
    build:
      context: ./packages/client/flutter_client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    networks:
      - mynetwork

  nginx:
    container_name: cvworld-nginx-server
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/var:/var/lib/letsencrypt
    depends_on:
      - server
      - client
      - phpmyadmin
    networks:
      - mynetwork

  adminer:
    container_name: cvworld-adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - 7777:80

  phpmyadmin:
    container_name: cvworld-phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    env_file:
      - ./packages/server/.env

  certbot:
    container_name: cvworld-certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/var:/var/lib/letsencrypt
    networks:
      - mynetwork
    command: certonly --webroot --webroot-path=/var/www/certbot --renew-by-default --email pawan.apexinfosys@gmail.com --agree-tos --no-eff-email -d cvworld.me -d www.cvworld.me


networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
