version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cvworld
      MYSQL_USER: cvworld
      MYSQL_PASSWORD: cvworld
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/cvworld
      - ADMIN_EMAIL=iampawanbhatia@gmail.com
      - ADMIN_PASSWORD=IamPawanbhatia@134
      - ADMIN_NAME=Pawan
      - JWT_SECRET=secret
      - RAZORPAY_KEY_ID=rzp_test_PYD4xAkex4oV9g
      - RAZORPAY_KEY_SECRET=UzjzcIMtEJjNj8UWjqZNRA93
      - RAZORPAY_WEBHOOK_SECRET=cvworld
      - IS_SERVERLESS=true
    command: sh -c "npx prisma migrate deploy && npm run start"
    volumes:
      - ./public:/app/public
    networks:
      - mynetwork

  client:
    build:
      context: ./packages/client/flutter_client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
