version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/cvworld
      - ADMIN_EMAIL=iampawanbhatia@gmail.com
      - ADMIN_PASSWORD=IamPawanbhatia@134
      - ADMIN_NAME=Pawan
      - JWT_SECRET=secret
      - RAZORPAY_KEY_ID=rzp_test_8kEpnyXnaJIirx
      - RAZORPAY_KEY_SECRET=2V20fgeMf2lUDhkOlKiOSodB
      - RAZORPAY_WEBHOOK_SECRET=cvworld
      - IS_SERVERLESS=true
      - BASE_URL=https://cvworld.me
    command: sh -c "npx prisma migrate deploy && npm run start"
    volumes:
      - ./public:/app/public
    networks:
      - mynetwork

  client:
    build:
      context: ./packages/client/flutter_client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/var:/var/lib/letsencrypt
    depends_on:
      - server
      - client
    networks:
      - mynetwork

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports:
      - 7777:8080

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/var:/var/lib/letsencrypt
    networks:
      - mynetwork
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email pawan.apexinfosys@gmail.com --agree-tos --no-eff-email -d cvworld.me -d www.cvworld.me


networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
