// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mlJE8tKepNsGt0PbryHkwPF-ayVDshE',
    appId: '1:526173453078:web:939d9e79a8c106d6e56e37',
    messagingSenderId: '526173453078',
    projectId: 'cvworld-400316',
    authDomain: 'cvworld-400316.firebaseapp.com',
    storageBucket: 'cvworld-400316.appspot.com',
    measurementId: 'G-X4D41H486X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfxaALcUg-UmWJjsEv19uWmYzZnx20K4',
    appId: '1:526173453078:android:03417e05e0537dd1e56e37',
    messagingSenderId: '526173453078',
    projectId: 'cvworld-400316',
    storageBucket: 'cvworld-400316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjkik1oNXW-EYMahnCkejUe8X6dBDIDys',
    appId: '1:526173453078:ios:12470ea1f9af5291e56e37',
    messagingSenderId: '526173453078',
    projectId: 'cvworld-400316',
    storageBucket: 'cvworld-400316.appspot.com',
    androidClientId: '526173453078-0b3n92piqmkt39ccl0oeoum0bhsb99aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjkik1oNXW-EYMahnCkejUe8X6dBDIDys',
    appId: '1:526173453078:ios:138974e2083cba12e56e37',
    messagingSenderId: '526173453078',
    projectId: 'cvworld-400316',
    storageBucket: 'cvworld-400316.appspot.com',
    androidClientId: '526173453078-0b3n92piqmkt39ccl0oeoum0bhsb99aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterClient.RunnerTests',
  );
}
